from building import *

cwd = GetCurrentDir()
src = Glob('*.c') + Glob('*.S')

if not GetDepend('BSP_USING_UART0') and not GetDepend('BSP_USING_UART1'):
    SrcRemove(src, ['drv_uart.c'])

if not GetDepend('BSP_USING_GPIO'):
    SrcRemove(src, ['drv_gpio.c'])

if not GetDepend('BSP_USING_WDT'):
    SrcRemove(src, ['drv_wdt.c'])

if not GetDepend('BSP_USING_TTC0_TIMER0'):
    SrcRemove(src, ['drv_ttc.c'])

if not GetDepend('BSP_USING_CAN0'):
    SrcRemove(src, ['drv_can.c'])

if not GetDepend('BSP_USING_QSPI0'):
    SrcRemove(src, ['drv_qspi.c'])

if not GetDepend('BSP_USING_USB0_HOST'):
    SrcRemove(src, ['drv_usb.c'])

if not GetDepend('BSP_USING_RGB_LCD'):
    SrcRemove(src, ['drv_lcd.c'])

if not GetDepend('BSP_USING_FT5246'):
    SrcRemove(src, ['drv_ft5246.c'])

if not GetDepend('BSP_USING_BOARD_KEYS'):
    SrcRemove(src, ['drv_keys.c'])

if not GetDepend('BSP_USING_GEM0'):
    SrcRemove(src, ['builtin_fdt.S', 'drv_gem_dma.c'])

group = DefineGroup('Drivers', src, depend=[''], CPPPATH=[cwd])

Return('group')
