from building import *

cwd = GetCurrentDir()
src = Glob('*.c') + Glob('*.S')

if not GetDepend('BSP_USING_UART0'):
    SrcRemove(src, ['drv_uart.c'])

if not GetDepend('BSP_USING_GPIO'):
    SrcRemove(src, ['drv_gpio.c'])

if not GetDepend('BSP_USING_WDT'):
    SrcRemove(src, ['drv_wdt.c'])

if not GetDepend('BSP_USING_TTC0_TIMER0'):
    SrcRemove(src, ['drv_ttc.c'])

if not GetDepend('BSP_USING_CAN0'):
    SrcRemove(src, ['drv_can.c'])

if not GetDepend('BSP_USING_GEM0'):
    SrcRemove(src, ['builtin_fdt.S', 'drv_gem_dma.c'])

group = DefineGroup('Drivers', src, depend=[''], CPPPATH=[cwd])

Return('group')
